/*
 * generated by Xtext 2.11.0
 */
package se.chalmers.turtlebotmission


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MissionDslStandaloneSetup extends MissionDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MissionDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
