/*
 * generated by Xtext 2.11.0
 */
package se.chalmers.turtlebotmission.ide


/**
 * Use this class to register ide components.
 */
class MissionDslIdeModule extends AbstractMissionDslIdeModule {
}
