/*
 * generated by Xtext 2.11.0
 */
package se.chalmers.turtlebotmission.idea.lang


class MissionDslFileType extends AbstractMissionDslFileType {
	public static final MissionDslFileType INSTANCE = new MissionDslFileType()
	
	new() {
		super(MissionDslLanguage.INSTANCE)
	}
}
