/*
 * generated by Xtext 2.11.0
 */
package se.chalmers.turtlebotmission.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import se.chalmers.turtlebotmission.idea.lang.MissionDslLanguage

class MissionDslCompletionContributor extends AbstractMissionDslCompletionContributor {
	new() {
		this(MissionDslLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
