/*
 * generated by Xtext 2.11.0
 */
package se.chalmers.turtlebotmission.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class MissionDslIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new MissionDslStandaloneSetupIdea().createInjector
	}

}
