/*
 * generated by Xtext 2.11.0
 */
package se.chalmers.turtlebotmission.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class MissionDslIdeaModule extends AbstractMissionDslIdeaModule {
}
